production: &production
  encryption_key: "<%= ENV['ENCRYPTION_KEY'] %>"
  attribute_encoding_key: "<%= ENV['ATTRIBUTE_ENCODING_KEY'] %>"
  redis_url: "<%= ENV['REDIS_URL'] %>"
  gear_translation_api:
    url: "<%= ENV['GEAR_TRANSLATION_API_URL'] %>"
    access_token: "<%= ENV['GEAR_TRANSLATION_API_ACCESS_TOKEN'] %>"

development: &development
  <<: *production
  redis_url: "redis://localhost:6379"
  bitbucket:
    user_name: "<%= ENV['BITBUCKET_USER_NAME'] %>"
    app_password: "<%= ENV['BITBUCKET_APP_PASSWORD'] %>"

test:
  <<: *development
  gear_translation_api:
    url: 'test_api_url'
    access_token: 'test_api_access_token'